site_name: Mimosa
nav:
  - Home: index.md
  - Installation: installation.md
  - Guided tour: simple_example.md
  - Language Definition:
    - Overview: overview.md
    - Types: types.md
    - Steps: steps.md
    - Channels: channels.md
    - Nodes: nodes.md
  - Additional Information:
    - License: license.md
theme: readthedocs
