site_name: Mimosa
nav:
  - Home: index.md
  - Installation: installation.md
  - Guided tour: simple_example.md
  - Language Definition:
    - Overview: overview.md
    - Types: types.md
    - Steps: steps.md
    - Channels: channels.md
    - Nodes: nodes.md
  - License: license.md
theme:
  name: material
  icon:
    logo: material/glass-cocktail
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
